- destinations/adtech/facebook-ads.mdx
- sources/bquery.mdx
> [Doc]: facebook custom audience documentation

- guides/architecture/multiwoven-protocol.mdx
> Doc: stream protocol changes for batch

- api-reference/openapi.yml
- api-reference/reports/get_report.mdx
- mint.json
> doc: api for get report

- guides/architecture/multiwoven-protocol.mdx
> feat: add ratelimiting fields to protocol

- destinations/crm/hubspot.mdx
docs: Hubspot destination setup
> docs: Hubspot destination setup

- mint.json
- sources/postgresql.mdx
docs: Add PostgreSQL source connector doc
> docs: Add PostgreSQL source connector doc

- api-reference/openapi.yml
- api-reference/sync_records/get_sync_records.mdx
- api-reference/sync_runs/get_sync_runs.mdx
- mint.json
> doc: add the api reference for get syn runs and sync records api

- sources/databricks.mdx
> doc: Add source/databricks

- .gitignore
- guides/architecture/sync-states.mdx
- mint.json
> doc: add sync state

- guides/architecture/introduction.mdx
Changed the text to be more consistent and grammatically accurate
> Fixed Grammatical and Spelling mistakes in Architecture Overview doc

- destinations/productivity-tools/google-sheets.mdx
- mint.json
doc: Add google sheets doc for service account based setup
> doc: Add google sheets doc for service account based setup

- guides/setup/environment-variables.mdx
Added envs required to be able to run community edition of Multiwoven.
> feat: added env for community edition

- guides/setup/environment-variables.mdx
docs: Add docs for SMTP ENV configurations
> docs: Add docs for SMTP ENV configurations

- destinations/payment/stripe.mdx
- mint.json
doc: Stripe destination connector
> doc: Stripe destination connector

- api-reference/openapi.yml
add cursor_field in sync create api
https://multiwoven-74-doc-sync-create-api-changes.mintlify.app/api-reference/syncs/create_sync
> doc:  add cursor_field in sync create api

- api-reference/openapi.yml
> Revert "doc: query_type in connector apis"

- api-reference/openapi.yml
https://github.com/Multiwoven/multiwoven/pull/75
https://github.com/Multiwoven/multiwoven/pull/71
> doc: api changes for sync and sync run

- destinations/retail/salesforce-consumer-goods-cloud.mdx
- mint.json
- sources/salesforce-consumer-goods-cloud.mdx
docs: Salesforce Consumer Goods Cloud Source/Destination
> docs: Salesforce Consumer Goods Cloud Source/Destination

- community-support/release-process.mdx
> docs: Update release process

- guides/setup/environment-variables.mdx
- guides/setup/helm.mdx
docs: added temporal.enabled to configuration
> docs: added temporal.enabled to configuration

- guides/setup/helm.mdx
docs: worker parameter for health check port
> docs: worker parameter for health check port

- open-source/guides/setup/aks.mdx
docs: added documentation for AKS configuration and deployment
> feature: adding aks configuration docs

- open-source/guides/setup/helm.mdx
docs: added additional installation information to helm.mdx and updated the example installation commands.
> fix: added additional installation information to the helm.mdx file

- open-source/guides/setup/environment-variables.mdx
docs: added new VITE_FAV_ICON_URL env var
> docs: add new VITE_FAV_ICON_URL env var

- guides/data-integration/sources/aws_athena.mdx
- mint.json
documentation for AWS Athena Connector
> docs: added documentation for AWS Athena Connector

- open-source/guides/setup/environment-variables.mdx
- open-source/guides/setup/helm.mdx
1. Added missing environment values for VITE (frontend).
2. Added environment variables for AppSignal and Rails log level.
3. Added helm chart values for Vite, AppSignal, and Rails log level.
> docs: updated env vars and helm chart values

- open-source/guides/setup/helm.mdx
Adding smtpSenderEMail and smtpBrandName helm values.
> docs: adding SMTP sender email and brand name helm values

- guides/data-integration/sources/clickhouse.mdx
- mint.json
documentation for ClickHouse Connector
> docs: added documentation for ClickHouse Connector

- open-source/guides/setup/ec2.mdx
docs: updated EC2 + docker-compose deployment guide for EE
> feature: update EC2 + docker-compose deployment doc

- guides/data-integration/destinations/marketing-automation/iterable.mdx
- mint.json
added documentation for Iterable Connector
> docs: added documentation for Iterable Connector

- open-source/guides/setup/environment-variables.mdx
> chore(CE): add host env variable

- open-source/guides/setup/ec2.mdx
docs: added ALLOWED_HOST instructions to ec2 walkthrough
> feature: added ALLOWED_HOST to ec2 walkthrough

- guides/data-integration/destinations/database/oracle.mdx
- mint.json
docs: added documentation for Oracle
> docs: added documentation for Oracle Destination

- guides/data-integration/destinations/productivity-tools/microsoft-excel.mdx
- mint.json
add documentation for Microsoft excel
> docs: add documentation for Microsoft excel

- guides/ai-ml-integration/Data_Apps.mdx
- guides/ai-ml-integration/Models.mdx
- guides/ai-ml-integration/Sources.mdx
- mint.json
- release-notes/2024.mdx
Updated mint.json to add pages for Sources, Models and Data Apps, under AI/ML Integrations 
Updated release/2024.mdx with to reflect version changes eg: "Version v0.14.0 to v0.19.0"
> feat: updated release notes and ai/ml integrations

- guides/data-integration/sources/aws_sagemaker-model.mdx
- mint.json
add documentation for AWS Sagemaker Model
> docs: add documentation for AWS Sagemaker Model

- help-and-resources/faqs/security.mdx
- mint.json
Added Security Info to FAQs section of docs.squared.ai. 
**Reviewers, please also evaluate if this information was placed in the correct section of docs.squared.ai.**
___
documentation
___
- Added a new FAQ page titled "Security at AI Squared" to the documentation.
- Detailed AI Squared's SOC 2 Type II certification and security practices.
- Provided information on data encryption and infrastructure security.
- Included a section on reporting vulnerabilities with contact information.
- Updated `mint.json` to include the new security page in the FAQs section.
___
<tr>
<td>
<details>
<summary><strong>security.mdx</strong><dd><code>Add Security Information …
> Feature  add security information

- guides/data-integration/sources/google_vertex-model.mdx
- mint.json
add documentation for Google Vertex Model
> docs: add documentation for Google Vertex Model

- guides/data-integration/destinations/database/ms_sql.mdx
- mint.json
Documentation
___
- Added a comprehensive guide for setting up a Microsoft SQL destination connector in AI Squared, including configuration steps and testing procedures.
- Updated `mint.json` to include the new Microsoft SQL guide in the list of available guides.
___
<tr>
<td>
<details>
<summary><strong>ms_sql.mdx</strong><dd><code>Add Microsoft SQL Destination Connector Guide</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
guides/data-integration/destinations/database/ms_sql.mdx
<li>Added a guide for setting up a Microsoft SQL destination connector.<br> <li> Included detailed steps for …
> doc: ms sql destination connector guide

- open-source/guides/setup/environment-variables.mdx
documentation
___
- Added documentation for a new environment variable `USER_EMAIL_VERFICATION` in the setup guide.
- Explained the purpose of the variable and the importance of configuring SMTP credentials correctly when it is set to true.
___
<tr>
<td>
<details>
<summary><strong>environment-variables.mdx</strong><dd><code>Document `USER_EMAIL_VERFICATION` environment variable</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
open-source/guides/setup/environment-variables.mdx
<li>Added documentation for <code>USER_EMAIL_VERFICATION</code> environment variable.<br> <li> Described its purpose and configuration requirements.<br>
</details>
</td>
<td><a …
> chore(CE): add email verification env variable

- open-source/guides/setup/helm.mdx
Updating docs with new helm-chart values for multiwoven worker host and port.
___
Documentation
___
- Updated the Helm chart documentation to include new configuration options for the Multiwoven worker service.
- Added `multiwovenConfig.workerHost` to specify the worker host.
- Detailed the port configuration for the Multiwoven worker, including port name, port number, and target port.
- Included the service type configuration for the Multiwoven worker, set to `ClusterIP`.
___
<tr>
<td>
<details>
<summary><strong>helm.mdx</strong><dd><code>Update Helm chart documentation with worker service configurations</code></dd></summary>
<hr> …
> doc: updated with multiwoven worker host and port

- mint.json
- release-notes/2024.mdx
- release-notes/August_2024.mdx
- release-notes/July_2024.mdx
- release-notes/June_2024.mdx
- release-notes/May_2024.mdx
- release-notes/October_2024.mdx
- release-notes/September_2024.mdx
Add Cards for the Month of September and October 
Update release notes for September and October. 
https://github.com/user-attachments/assets/61941516-aaff-4cf5-a5c3-e7e5aba00042
___
Documentation
___
- Added new release notes for September and October 2024, documenting new features and improvements.
- Updated existing release notes for May, June, July, and August 2024 with revised descriptions and section titles.
- Updated JSON configuration to include new release notes pages and reordered existing entries.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>mint.json</strong><dd><code>Update release notes and AI Activation guides in JSON …
> Release documentation updates September and October

- guides/data-integration/sources/http-model-endpoint.mdx
- mint.json
add documentation for HTTP Model
___
Documentation
___
- Added a comprehensive guide for configuring the HTTP Model Connector in AI Squared, including prerequisites, setup steps, and testing.
- Updated the `mint.json` file to include the new HTTP Model Endpoint guide in the list of data integration sources.
___
<tr>
<td>
<details>
<summary><strong>http-model-endpoint.mdx</strong><dd><code>Add guide for HTTP Model Connector configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
guides/data-integration/sources/http-model-endpoint.mdx
<li>Added a new guide for configuring HTTP Model Connector.<br> <li> …
> docs: add documentation for HTTP Model

- mint.json
- release-notes/2024.mdx
- release-notes/November_2024.mdx
- release-notes/September_2024.mdx
Consolidated November release documentation
___
Documentation, Enhancement
___
- Added a new entry in `mint.json` for November 2024 release notes.
- Updated `release-notes/2024.mdx` to include a card for November 2024.
- Created a comprehensive document for November 2024 release notes, detailing new features, improvements, and miscellaneous updates.
___
<tr>
<td>
<details>
<summary><strong>mint.json</strong><dd><code>Update release notes section with November 2024</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
mint.json
- Added a new entry for November 2024 release notes.
</details>
</td>
<td><a …
> Release notes for November

- guides/data-integration/sources/sftp.mdx
- mint.json
https://linear.app/ai-squared/issue/BE-729/doc-sftp-source-connector
___
Documentation
___
- Added a new guide for configuring the SFTP source connector.
- Detailed step-by-step instructions for SFTP setup.
- Included supported sync modes for the SFTP connector.
- Updated `mint.json` to include the SFTP guide in the documentation structure.
___
<tr>
<td>
<details>
<summary><strong>sftp.mdx</strong><dd><code>Add SFTP source connector documentation guide</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
guides/data-integration/sources/sftp.mdx
<li>Added a new guide for SFTP source connector.<br> …
> docs: Add SFTP Source doc

- mint.json
- release-notes/2024.mdx
- release-notes/December_2024.mdx
Add consolidated release notes for moth of December.
https://github.com/user-attachments/assets/bfb5f0c6-0dbd-4115-b0e0-d406962df946
___
Documentation
___
- Added release notes for December 2024, detailing features and improvements.
- Updated `mint.json` to include the December 2024 release notes page.
- Enhanced the release notes overview with a card for December 2024.
- Documented new features, bug fixes, and enhancements for December 2024.
___
<tr>
<td>
<details>
<summary><strong>mint.json</strong><dd><code>Include December 2024 in release notes group</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Docs:Update release notes for December

- guides/data-integration/destinations/file-storage/amazon_s3.mdx
- mint.json
Documentation
___
- Added a comprehensive guide for configuring Amazon S3 as a destination.
- Included step-by-step instructions for AWS setup and connector configuration.
- Added images to illustrate key steps in the guide.
- Updated `mint.json` to include the new Amazon S3 guide in the documentation structure.
___
<tr>
<td>
<details>
<summary><strong>amazon_s3.mdx</strong><dd><code>Added Amazon S3 destination integration guide</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
guides/data-integration/destinations/file-storage/amazon_s3.mdx
<li>Added a new guide for Amazon S3 integration.<br> …
> docs: Add Amazon S3 Destination Document

- open-source/guides/setup/avm.mdx
- open-source/guides/setup/docker-compose.mdx
- open-source/guides/setup/ec2.mdx
- open-source/guides/setup/gce.mdx
- Added TLS requirement to docker compose production deployment
- Fixed typos of port nos.
> update deployment steps

- mint.json
> Production FIX

- .gitignore
- activation/ai-ml-sources/aws_bedrock-model.mdx
- mint.json
> docs: Add AWS Bedrock documentation

- activation/ai-ml-sources/generic_open_ai-endpoint.mdx
- mint.json
add Generic Open AI Documentation
> doc: add Generic Open AI Documentation

- guides/destinations/retl-destinations/database/qdrant.mdx
- mint.json
Adds documentation for the Qdrant destination connector.
> doc: Add Qdrant documentation

- guides/sources/data-sources/intuit_quickbooks.mdx
- mint.json
add Intuit QuickBooks Documentation
> doc: add Intuit QuickBooks Documentation

- activation/vector-search/qdrant.mdx
- mint.json
> doc: Add Qdrant Vector Search Source documentation
